---
## MLP Parameters ##
dataset: /local/cifar10-th/
model_file: all-cnn.model
optimizer:
  class_name: WAME
  config:
    lr:
      0:  0.001
      40: 0.0001
    decay: 1e-5
n_epochs: 100 #max number of training epochs
batch_size: 128
cost_function: categorical_crossentropy
shuffle_dataset: true
join_train_and_valid: true
online_transform:
    #    pad: [40, 40]
#    crop: [32, 32]   
    horizontal_flip: true
#    featurewise_center: true
#    featurewise_std_normalization: true
#    rotation_range: 10
#    height_shift_range: 0.1
#    width_shift_range: 0.1
#    after_epoch: 30
#    rotation_range: 10
#    zoom_range: 0.2
    height_shift_range: 0.125
    width_shift_range: 0.125
#    shear_range: 0.75


## Ensemble Parameters ##
resample_size: 50000
method: !Bagging { }
ensemble_size: 10
