---
## MLP Parameters ##
dataset: /local/cifar10_whitened_torch/
model_file: wide-resnet-different.model
optimizer:
    class_name: SGD
    config:
        lr:
            0:   0.1
            60:  0.02
            120: 0.004
            160: 0.008
    decay: 0
    momentum: 0.9
    nesterov: True
n_epochs: 200 #max number of training epochs
batch_size: 128
cost_function: categorical_crossentropy
shuffle_dataset: true
join_train_and_valid: false
one_hot: true
online_transform:
    pad: [40, 40]
    crop: [32, 32]
    horizontal_flip: true
#    vertical_flip: false
#    height_shift_range: 0.1
#    width_shift_range: 0.1
#    after_epoch: 30
    rotation_range: 10
#    zoom_range: 0.2
    height_shift_range: 0.1
    width_shift_range: 0.1
#    zca_whitening: true
#    shear_range: 0.75
#    elastic_transform:
#        alpha: 8
#        sigma: 5

## Ensemble Parameters ##
resample_size: 50000
method: !Bagging {}
ensemble_size: 5
