---
## MLP Parameters ##
dataset: /local/tiny-imagenet-200/
model_file: all-cnn.model
optimizer:
  class_name: WAME
  config:
    lr:
      0:  0.001
      30: 0.0005
      60: 0.0001
    decay: 1e-5
n_epochs: 100
batch_size: 128
cost_function: categorical_crossentropy
shuffle_dataset: true
join_train_and_valid: false
one_hot: true

## Ensemble Parameters ##
resample_size: 50000
method: !BARN
    n_epochs_after_first: 10
    freeze_old_layers: false
    incremental_index: 31
    incremental_layers:
        - class_name: BatchNormalization
          config:
            axis: 1
            beta_constraint: null
            beta_initializer:
              class_name: Zeros
              config: {}
            beta_regularizer: null
            center: true
            epsilon: 0.001
            gamma_constraint: null
            gamma_initializer:
              class_name: Ones
              config: {}
            gamma_regularizer: null
            momentum: 0.99
            moving_mean_initializer:
              class_name: Zeros
              config: {}
            moving_variance_initializer:
              class_name: Ones
              config: {}
            name: batch_normalization_1
            scale: true
            trainable: true
        - class_name: Activation
          config: {activation: relu, name: activation_5, trainable: true}
        - class_name: Conv2D
          config:
            activation: linear
            activity_regularizer: null
            bias_constraint: null
            bias_initializer:
              class_name: VarianceScaling
              config: {distribution: normal, mode: fan_in, scale: 2.0, seed: null}
            bias_regularizer:
              class_name: L1L2
              config: {l1: 0.0, l2: 9.999999747378752e-05}
            data_format: channels_first
            dilation_rate: &id001 !!python/tuple [1, 1]
            filters: 192
            kernel_constraint: null
            kernel_initializer:
              class_name: VarianceScaling
              config: {distribution: normal, mode: fan_in, scale: 2.0, seed: null}
            kernel_regularizer:
              class_name: L1L2
              config: {l1: 0.0, l2: 9.999999747378752e-05}
            kernel_size: !!python/tuple [3, 3]
            name: conv2d_1
            padding: same
            strides: &id002 !!python/tuple [1, 1]
            trainable: true
            use_bias: true
        - class_name: BatchNormalization
          config:
            axis: 1
            beta_constraint: null
            beta_initializer:
              class_name: Zeros
              config: {}
            beta_regularizer: null
            center: true
            epsilon: 0.001
            gamma_constraint: null
            gamma_initializer:
              class_name: Ones
              config: {}
            gamma_regularizer: null
            momentum: 0.99
            moving_mean_initializer:
              class_name: Zeros
              config: {}
            moving_variance_initializer:
              class_name: Ones
              config: {}
            name: batch_normalization_1
            scale: true
            trainable: true
        - class_name: Activation
          config: {activation: relu, name: activation_6, trainable: true}
        - class_name: Conv2D
          config:
            activation: linear
            activity_regularizer: null
            bias_constraint: null
            bias_initializer:
              class_name: VarianceScaling
              config: {distribution: normal, mode: fan_in, scale: 2.0, seed: null}
            bias_regularizer:
              class_name: L1L2
              config: {l1: 0.0, l2: 9.999999747378752e-05}
            data_format: channels_first
            dilation_rate: *id001
            filters: 192
            kernel_constraint: null
            kernel_initializer:
              class_name: VarianceScaling
              config: {distribution: normal, mode: fan_in, scale: 2.0, seed: null}
            kernel_regularizer:
              class_name: L1L2
              config: {l1: 0.0, l2: 9.999999747378752e-05}
            kernel_size: !!python/tuple [3, 3]
            name: conv2d_1
            padding: same
            strides: *id002
            trainable: true
            use_bias: true
ensemble_size: 10
