---
## MLP Parameters ##
dataset: /datasets/tinyimagenet/
model_file: all-cnn.model
optimizer:
  class_name: RMSProp
  config:
    lr:
      0:  0.001
      30: 0.0005
      60: 0.0001
    decay: 0.00001
n_epochs: 100
batch_size: 256
cost_function: categorical_crossentropy
shuffle_dataset: true
join_train_and_valid: false
one_hot: true

## Ensemble Parameters ##
resample_size: 100000
method: !BRN
    real: true
    n_epochs_after_first: 10
    freeze_old_layers: false
    incremental_index: 31
    incremental_layers: !include incremental_layers.yaml
ensemble_size: 30
