---
## MLP Parameters ##
dataset: /local/mnist_th/
model_file: mnist.model
optimizer:
  class_name: ARMSprop
  config:
    lr:
        0:  0.001
        11: 0.0001
        16: 0.00001
#        40: 0.00001
    decay: 1e-4
n_epochs: 100 #max number of training epochs
batch_size: 128
cost_function: categorical_crossentropy
shuffle_dataset: true
#online_transform:
#    horizontal_flip: true
#    rotation_range: 20
#    zoom_range: 0.2
#    height_shift_range: 0.1
#    width_shift_range: 0.1
#    shear_range: 7.5
#    elastic_transform:
#        alpha: 8
#        sigma: 5

## Ensemble Parameters ##
resample_size: 60000
method: !Bagging {}
ensemble_size: 1
