---
## MLP Parameters ##
dataset: /local/cifar100-th/
model_file: all-cnn.model
optimizer:
  class_name: WAME
  config:
    lr: 0.001
    decay: 1e-5
n_epochs: 100 #max number of training epochs
batch_size: 256
cost_function: categorical_crossentropy
join_train_and_valid: true
shuffle_dataset: true
online_transform:
    horizontal_flip: true
    vertical_flip: false
    rotation_range: 10
    height_shift_range: 0.1
    width_shift_range: 0.1
## Ensemble Parameters ##
resample_size: 40000
method: !Bagging {}
ensemble_size: 10
