---
## MLP Parameters ##
dataset: /local/cifar10_whitened_torch/
model_file: all-cnn.model
optimizer:
  class_name: WAME
  config:
    lr:
      0:  0.001
      20: 0.0005
      60: 0.0001
    decay: 1e-5
n_epochs: 100
batch_size: 128
cost_function: categorical_crossentropy
shuffle_dataset: true
join_train_and_valid: false
one_hot: true
test_at_each_epoch: false
#online_transform:
#    horizontal_flip: true
#    vertical_flip: false
#    rotation_range: 10
#    height_shift_range: 0.1
#    width_shift_range: 0.1

## Ensemble Parameters ##
resample_size: 50000
method: !DIB
    n_epochs_after_first: 10
    freeze_old_layers: false
    incremental_index: 36
    incremental_layers:
        - class_name: BatchNormalization
          config: {axis: 1, beta_regularizer: null, epsilon: 1.0e-05, gamma_regularizer: null,
            mode: 2, momentum: 0.99, name: batchnormalization_5, trainable: true}
        - class_name: Activation
          config: {activation: relu, name: activation_5, trainable: true}
        - class_name: Convolution2D
          config:
            W_constraint: null
            W_regularizer: {l1: 0.0, l2: 9.999999747378752e-05, name: WeightRegularizer}
            activation: linear
            activity_regularizer: null
            b_constraint: null
            b_regularizer: {l1: 0.0, l2: 9.999999747378752e-05, name: WeightRegularizer}
            bias: true
            border_mode: same
            dim_ordering: th
            init: he_normal
            name: convolution2d_5
            nb_col: 3
            nb_filter: 192
            nb_row: 3
            subsample: !!python/tuple [1, 1]
            trainable: true
        - class_name: BatchNormalization
          config: {axis: 1, beta_regularizer: null, epsilon: 1.0e-05, gamma_regularizer: null,
            mode: 2, momentum: 0.99, name: batchnormalization_6, trainable: true}
        - class_name: Activation
          config: {activation: relu, name: activation_6, trainable: true}
        - class_name: Convolution2D
          config:
            W_constraint: null
            W_regularizer: {l1: 0.0, l2: 9.999999747378752e-05, name: WeightRegularizer}
            activation: linear
            activity_regularizer: null
            b_constraint: null
            b_regularizer: {l1: 0.0, l2: 9.999999747378752e-05, name: WeightRegularizer}
            bias: true
            border_mode: same
            dim_ordering: th
            init: he_normal
            name: convolution2d_6
            nb_col: 3
            nb_filter: 192
            nb_row: 3
            subsample: !!python/tuple [1, 1]
            trainable: true
ensemble_size: 10
