---
## MLP Parameters ##
dataset: /local/cifar100-th/
model_file: all-cnn.model
optimizer:
  class_name: WAME
  config:
    lr:
      0:  0.001
      40: 0.0001
    decay: 1e-5
n_epochs: 100
batch_size: 128
cost_function: categorical_crossentropy
shuffle_dataset: true
join_train_and_valid: true

## Ensemble Parameters ##
resample_size: 50000
method: !Bagging { }
ensemble_size: 10
