---
## MLP Parameters ##
dataset: /local/cifar10-gcn-augmented_th/
model_file: all-cnn.model
optimizer:
  class_name: ARMSProp
  config:
    lr: 0.001
    decay: 1e-5
n_epochs: 50 #max number of training epochs
batch_size: 256
cost_function: categorical_crossentropy
shuffle_dataset: true
join_train_and_valid: true
online_transform:
    horizontal_flip: true
    vertical_flip: false
    rotation_range: 10
    height_shift_range: 0.1
    width_shift_range: 0.1

## Ensemble Parameters ##
resample_size: 50000
method: !AdaBoostM1 { }
ensemble_size: 10
