---
## Network Parameters ##
dataset: ~/cifar-10-new-loaded/
model_file: densenet121.model
optimizer: !include optimizer.yaml
reduce_lr_on_plateau:
  factor: 0.1
  patience: 5
  cooldown: 0
  min_lr: 0.0000001
data_format: npz
convert_labels_to_one_hot: true
epochs: 100
batch_size: 128
loss: categorical_crossentropy
shuffle: true
img_gen_params: !include img_gen.yaml


## Ensemble Parameters ##
ensemble_method:
  class_name: Bagging
  params:
    aggregator: Averaging
    size: 20